DROP TABLE IF EXISTS Pelaaja CASCADE;
DROP TABLE IF EXISTS Rata CASCADE;
DROP TABLE IF EXISTS Tulos CASCADE;
DROP TABLE IF EXISTS RadanPelaajat CASCADE;
DROP TABLE IF EXISTS Vayla CASCADE;
DROP TABLE IF EXISTS VaylaTulos CASCADE;
